version: '3'
services: 
    web:
        build: .
        restart: always
        ports: 
            - 1234:8000
        depends_on:
            - db
            - redis
            - celery

    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
            
    redis:
        image: "redis:alpine"
        restart: always
        command: redis-server
        ports:
            - '6379:6379'
        
    celery:
        build: .
        command: celery -A backend.core worker -l info
        depends_on:
            - redis
        volumes:
            - .:/app
