version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'

  celery:
    build: .
    entrypoint: celery -A backend.core worker -l info
    environment:
      - DEBUG=False
      - POSTGRESQL_DB_HOST=db
      - POSTGRESQL_DB_NAME=postgres
      - POSTGRESQL_DB_USER_NAME=postgres
      - POSTGRESQL_DB_USER_PASS=postgres
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis

  backend:
    build:
      context: .
    environment:
      - POSTGRESQL_DB_HOST=db
      - POSTGRESQL_DB_NAME=postgres
      - POSTGRESQL_DB_USER_NAME=postgres
      - POSTGRESQL_DB_USER_PASS=postgres
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - db
      - redis
      - celery
    ports:
      - 5000:5000

  frontend:
    build:
      context: frontend
    ports:
      - 8083:80
    depends_on:
      - backend


volumes:
  postgres_data: