version: '3.7'
services: 
    db:
        image: postgres:10.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        restart: always
        command: redis-server
        ports:
            - '6379:6379'
        
    celery:
        build: .
        command: celery -A backend.core worker -l info
        depends_on:
            - redis
        volumes:
            - .:/app
    web:
        build: .
        ports: 
            - 1234:8000
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
            - celery

volumes:
    postgres_data: