apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mentabook
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.1-alpine
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name:  postgres-pv
            mountPath:  /var/lib/postgresql/data/
        ports:
        - containerPort: 5432
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: pvc-claim-small
